admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  listeners:
    name: listener_0
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 6379
    filter_chains:
      filters:
        name: envoy.filters.network.redis_proxy
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
          stat_prefix: redis_stats
          prefix_routes:
            catch_all_route:
              cluster: cluster_0
          settings:
            op_timeout: 5s
            enable_redirection: true
            enable_hashtagging: true
  clusters:
    - name: cluster_0
      lb_policy: CLUSTER_PROVIDED
      dns_lookup_family: V4_ONLY
      load_assignment:
        cluster_name: cluster_0
        endpoints:
        - lb_endpoints:
          - endpoint:
              address:
                socket_address:
                  address: redis-{name}.{namespace}.svc.cluster.local
                  port_value: 6379
      cluster_type:
        name: envoy.clusters.redis
        typed_config:
          "@type": type.googleapis.com/google.protobuf.Struct
          value:
            cluster_refresh_rate: 30s
            cluster_refresh_timeout: 0.5s
            redirect_refresh_interval: 10s
            redirect_refresh_threshold: 10
