apiVersion: v1
kind: Service
metadata:
  name: redis-{name}
  labels:
    database: redis
    cluster: {name}
spec:
  selector:
    database: redis
    cluster: {name}
  clusterIP: None
  ports:
  - name: redis
    port: 6379
