apiVersion: v1
kind: Service
metadata:
  name: redis-proxy
  labels:
    database: redis
    cluster: c0
spec:
  selector:
    database: redis
    cluster: c0
    role: proxy
  ports:
  - name: redis
    port: 6379
