apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labelers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: labeler
subjects:
- kind: ServiceAccount
  name: redis
