apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  labels:
    database: redis
    server: s0
    shard-role: primary
spec:
  selector:
    database: redis
    server: s0
    shard-role: primary
  clusterIP: None
  ports:
  - name: redis
    protocol: TCP
    port: 6379
